language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

env:
  - SYMFONY_VERSION=^3.0
  - SYMFONY_VERSION=^4.0

cache:
  directories:
    - $COMPOSER_CACHE_DIR

matrix:
  exclude:
    - php: 5.6
      env: SYMFONY_VERSION=^4.0
    - php: 7.0
      env: SYMFONY_VERSION=^4.0

before_install:
  - travis_retry composer selfupdate

before_script:
  - travis_wait composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update --prefer-source
  - travis_wait composer require symfony/http-kernel:${SYMFONY_VERSION} --no-update --prefer-source
  - travis_wait composer require symfony/security-bundle:${SYMFONY_VERSION} --no-update --prefer-source
  - travis_wait composer require symfony/security-acl:${SYMFONY_VERSION} --no-update --prefer-source
  - travis_wait composer install --dev --prefer-source

script: ./vendor/bin/phpunit
