language: php
sudo: false

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*

matrix:
  exclude:
    - php: 5.3
      env: SYMFONY_VERSION=3.0.*
    - php: 5.4
      env: SYMFONY_VERSION=3.0.*

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update --prefer-source
  - composer require symfony/http-kernel:${SYMFONY_VERSION} --no-update --prefer-source
  - composer require symfony/security-bundle:${SYMFONY_VERSION} --no-update --prefer-source
  - composer require symfony/security-acl:${SYMFONY_VERSION} --no-update --prefer-source
  - composer install --dev --prefer-source